### PR TITLE
Day2 viz exercise

### PR DESCRIPTION
**Pull request by dhuppenkothen**
Here's my first draft for the data visualization exercise for day 2. Suggestions/comments/improvements welcome!

 I've included the figures to be used in the exercise in a folder, but I'm wondering how appropriate/legal it is to include just the raw figures without attribution?

### CODE REVIEW

**Comment by adamamiller** [comment]
Before merging this - one change: the students have the full hour on Tuesday to work on this, they will be presenting their results on Wednesday.

Also - do you recall how we found all these figures? If they came from a single website maybe we can just attribute that?

**Comment by dhuppenkothen** [comment]
I'll make the changes and find the sources of the figures before I update the pull request.

**Comment by dhuppenkothen** [comment]
I've put the figures in a private folder on our NYU storage system that the participants should be able to access; I'll share the link on a slide. 

Thanks for the correction regarding the time for when they get to show their results. I messed that up in my head. Let me know if there are any additional comments!

**Comment by adamamiller** [comment]
One last (non-essential request) - can you git mv day2 to Day2 to match the formatting of every other day? Thanks.

**Pull request merged**
