### PR TITLE
Added 3 worksheets on GPs

### PR DESCRIPTION
**Pull request by rodluger**

### CODE REVIEW

**Comment by adamamiller** [comment]
We try to avoid storing data in the github repo - can you resubmit without the data files (and send those to me separately - I can then provide a download link for the notebook).

**Comment by rodluger** [comment]
Ok, I removed the datasets and added ``!wget`` commands to the top of the notebooks to download them as needed, so we should be all set.

**Comment by adamamiller** [comment]
I might copy the data to our persistent file sources (at Northwestern) and change up the links, but merging the request in the meantime.

**Comment by rodluger** [comment]
Fine by me!

**Pull request merged**
